# Generated by Django 5.2.8 on 2025-11-24 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('type', models.CharField(choices=[('university', 'Universidade'), ('health_school', 'Escola de Saúde Pública')], max_length=20, verbose_name='Tipo')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_users', models.ManyToManyField(related_name='administered_institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='InternshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('original_file', models.FileField(upload_to='documents/original/%Y/%m/', verbose_name='Arquivo Original (PDF)')),
                ('original_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 do Original')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='documents/signed/%Y/%m/', verbose_name='Arquivo Assinado (PDF)')),
                ('status', models.CharField(choices=[('pending_health_school', 'Aguardando Escola de Saúde'), ('signed_health_school', 'Assinado pela Escola de Saúde'), ('completed', 'Processo Concluído'), ('rejected', 'Rejeitado')], default='pending_health_school', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('num_students', models.IntegerField(default=0, verbose_name='Número de Estudantes')),
                ('student_info', models.TextField(blank=True, verbose_name='Informações dos Estudantes (JSON)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('health_school', models.ForeignKey(limit_choices_to={'type': 'health_school'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to='fluxo.institution', verbose_name='Escola de Saúde Destinatária')),
                ('university', models.ForeignKey(limit_choices_to={'type': 'university'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_documents', to='fluxo.institution', verbose_name='Universidade Remetente')),
            ],
            options={
                'verbose_name': 'Documento de Estágio',
                'verbose_name_plural': 'Documentos de Estágio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Documento Criado'), ('sent', 'Documento Enviado'), ('signed', 'Documento Assinado'), ('rejected', 'Documento Rejeitado'), ('completed', 'Processo Concluído')], max_length=20, verbose_name='Ação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fluxo.internshipdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Histórico do Documento',
                'verbose_name_plural': 'Históricos dos Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_type', models.CharField(choices=[('university', 'Representante da Universidade'), ('health_school', 'Representante da Escola de Saúde')], max_length=20, verbose_name='Tipo de Signatário')),
                ('signature_data', models.TextField(verbose_name='Dados da Assinatura (JSON)')),
                ('signature_hash', models.CharField(max_length=64, verbose_name='Hash da Assinatura')),
                ('certificate_data', models.TextField(blank=True, verbose_name='Dados do Certificado Digital')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assinado em')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('signer_name', models.CharField(max_length=200, verbose_name='Nome do Signatário')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Email do Signatário')),
                ('signer_cpf', models.CharField(max_length=14, verbose_name='CPF do Signatário')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Signatário')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='fluxo.internshipdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'ordering': ['-signed_at'],
            },
        ),
    ]
